#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model BouncingBall
 Dymola Version 2021x (64-bit), 2020-10-09 translated this at Thu May 27 17:21:02 2021

   */
#define DAEsolver_ 1

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    2
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    0
#define NP_    2
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -1844745673
#define NHash2_ -639826833
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  1
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 1
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 1
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="BouncingBall";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[6]={1 , 2 , 1 , 2 , 0 , 0};
static int QJacobianGrp0[3]={2, 0, 0};
DYMOLA_STATIC struct QJacobianTag_ QJacobianGC2_[2]={
{0, QJacobianGrp0},{0,0}};
DYMOLA_STATIC double QJacobianCD_[3]={0  , 44 , 55};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(F_,0) = 0.0;
#endif
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(F_,1) = -9.81;
DYNX(X_,0) = DYNX(DP_,1);
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(F_,1) = -9.81;
DYNX(F_,0) = DYNX(X_,1);

AcceptedSection1

AcceptedSection2

DefaultSection
CrossingSection
/* Start of reinit equations */
beginwhenBlock
whenModelica(LessMinor(DYNX(X_,0),"h", 0,"0", 0), 0) 
  reinit(DYNX(X_,1),  -DYNX(DP_,0)*PRE(DYNX(X_,1), 0));
endwhenModelica()
endwhenBlock


/* End of reinit equations */
DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("e", "Coefficient of restitution [1]", 0, 0.8, 0.0,0.0,0.0,0,560)
DeclareParameter("h0", "Initial height [m]", 1, 1.0, 0.0,0.0,0.0,0,560)
DeclareState("h", "Height [m]", 0, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("der(h)", "der(Height) [m/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("v", "Velocity [m/s]", 1, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(v)", "der(Velocity) [m/s2]", 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartPreBlock
preCont(DYNX(X_,1),"v", 0.0, 0);
EndPreBlock
UpdateQEvaluate(1)
EndDataBlock
