#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model BouncingBall
 Dymola Version 2021x (64-bit), 2020-10-09 translated this at Fri Jun  4 13:55:57 2021

   */
#define DAEsolver_ 1

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    2
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    6
#define NP_    11
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 753311701
#define NHash2_ -2007637137
#define NHash3_ 0
#define NI_    0
#define NRelF_ 1
#define NRel_  2
#define NTim_  4
#define NSamp_ 0
#define NCons_ 0
#define NA_    1
#define SizePre_ 2
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 2
#define NrDymolaTimers_ 0
#define NWhen_ 2
#define NCheckIf_ 0
#define NGlobalHelp_ 2
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="BouncingBall";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[6]={1 , 2 , 1 , 2 , 0 , 0};
static int QJacobianGrp0[3]={2, 0, 0};
DYMOLA_STATIC struct QJacobianTag_ QJacobianGC2_[2]={
{0, QJacobianGrp0},{0,0}};
DYMOLA_STATIC double QJacobianCD_[3]={0  , 44 , 55};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(W_,1) = DYNX(DP_,3);
DYNX(W_,2) = DYNX(W_,1)+DYNX(DP_,4);
DYNX(W_,3) = DYNX(W_,2)+DYNX(DP_,5);
InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(F_,0) = 0.0;
#endif
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialBoundSection
DYNX(Aux_,0) = DYNX(W_,4);
DYNX(Aux_,1) = DYNX(W_,5);
InitialSection
InitialSection2
DYNX(F_,1) = -9.81;
  DYNX(W_,5) = real2integerEvent(divGuarded(DYNTime-DYNX(DP_,9),"time-variance.startTime",
    DYNX(DP_,6),"variance.period"),"(time-variance.startTime)/variance.period", 0);
  DYNX(W_,4) = DYNX(DP_,9)+DYNX(W_,5)*DYNX(DP_,6);
InitialBoundSection
DYNX(Aux_,0) = DYNX(W_,4);
InitialSection2
DYNX(X_,0) = DYNX(DP_,1);
InitialBoundSection
DYNX(Aux_,1) = DYNX(W_,5);
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(F_,1) = -9.81;
DYNX(F_,0) = DYNX(X_,1);

AcceptedSection1

AcceptedSection2
beginwhenBlock
if (NewParameters_) {
DYNX(DYNhelp,0) = divinvGuarded(DYNX(DP_,6),"variance.period");
}
DYNX(DYNhelp,1) = real2integer(DYNX(DYNhelp,0)*(DYNTime-DYNX(DP_,9)));
whenModelica(real2integerEventMinor(divGuarded(DYNTime-DYNX(DP_,9),
  "time-variance.startTime",DYNX(DP_,6),"variance.period"),"(time-variance.startTime)/variance.period",
   0) > PRE(DYNX(W_,5), 0), 0) 
  DYNX(W_,4) = DYNTime;
  DYNX(W_,5) = PRE(DYNX(W_,5), 0)+1;
endwhenModelica()
endwhenBlock


DYNX(W_,0) = DYNX(DP_,8)+(IF LessTime(DYNX(DP_,9), 0) OR DYNX(DP_,7) == 0 OR 
  DYNX(DP_,7) > 0 AND DYNX(W_,5) >= DYNX(DP_,7) THEN 0 ELSE IF LessTime(
  DYNX(W_,4)+DYNX(W_,1), 1) THEN divGuarded(DYNX(DP_,2)*(DYNTime-DYNX(W_,4)),
  "variance.amplitude*(time-variance.T_start)",DYNX(DP_,3),"variance.rising")
   ELSE IF LessTime(DYNX(W_,4)+DYNX(W_,2), 2) THEN DYNX(DP_,2) ELSE IF LessTime(
  DYNX(W_,4)+DYNX(W_,3), 3) THEN divGuarded(DYNX(DP_,2)*(DYNX(W_,4)+DYNX(W_,3)-
  DYNTime),"variance.amplitude*(variance.T_start+variance.T_falling-time)",
  DYNX(DP_,5),"variance.falling") ELSE 0);

DefaultSection
CrossingSection
/* Start of reinit equations */
beginwhenBlock
whenModelica(LessMinor(DYNX(X_,0),"h", 0,"0", 1), 1) 
  reinit(DYNX(X_,1),  -DYNX(DP_,0)*PRE(DYNX(X_,1), 1));
endwhenModelica()
endwhenBlock


/* End of reinit equations */
DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("e", "Coefficient of restitution [1]", 0, 0.8, 0.0,0.0,0.0,0,560)
DeclareParameter("h0", "Initial height [m]", 1, 1.0, 0.0,0.0,0.0,0,560)
DeclareState("h", "Height [m]", 0, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("der(h)", "der(Height) [m/s]", 0.0, 0.0,0.0,0.0,0,512)
DeclareState("v", "Velocity [m/s]", 1, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(v)", "der(Velocity) [m/s2]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("variance.amplitude", "Amplitude of trapezoid", 2, 1, 0.0,0.0,\
0.0,0,560)
DeclareParameter("variance.rising", "Rising duration of trapezoid [s]", 3, 0, \
0.0,1E+100,0.0,0,560)
DeclareParameter("variance.width", "Width duration of trapezoid [s]", 4, 0.5, \
0.0,1E+100,0.0,0,560)
DeclareParameter("variance.falling", "Falling duration of trapezoid [s]", 5, 0, \
0.0,1E+100,0.0,0,560)
DeclareParameter("variance.period", "Time for one period [s]", 6, 1, 1E-60,\
1E+100,0.0,0,560)
DeclareParameter("variance.nperiod", "Number of periods (< 0 means infinite number of periods) [:#(type=Integer)]",\
 7, -1, 0.0,0.0,0.0,0,564)
DeclareVariable("variance.y", "Connector of Real output signal", 0.0, 0.0,0.0,\
0.0,0,512)
DeclareParameter("variance.offset", "Offset of output signal y", 8, 0, 0.0,0.0,\
0.0,0,560)
DeclareParameter("variance.startTime", "Output y = offset for time < startTime [s]",\
 9, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("variance.T_rising", "End time of rising phase within one period [s]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("variance.T_width", "End time of width phase within one period [s]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("variance.T_falling", "End time of falling phase within one period [s]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("variance.T_start", "Start time of current period [s]", 0.0, \
0.0,0.0,0.0,0,2688)
DeclareVariable("variance.count", "Period count [:#(type=Integer)]", 0, 0.0,0.0,\
0.0,0,2692)
DeclareParameter("test.k", "Constant output value", 10, 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("test.y", "Connector of Real output signal", "test.k", 1, 7, 10, 0)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartPreBlock
preCont(DYNX(X_,1),"v", 0.0, 1);
pre(DYNX(W_,5),"variance.count", 0, 0);
EndPreBlock
UpdateQEvaluate(2)
EndDataBlock
