#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model KundurSMIB.SMIB
 Dymola Version 2021x (64-bit), 2020-10-09 translated this at Thu Apr 22 20:16:16 2021

   */

#include <matrixop.h>
#if defined(DynSimStruct) || defined(BUILDFMU)
static double DymArrays1[3]={0.57, 100.0, 1.0};
static double DymArrays0[3]={1E+60, 1E+60, 1.0};
#endif
/* Declaration of C-structs */
/* Prototypes for functions used in model */
DYMOLA_STATIC double   Modelica_Math_atan3(double  u10_0, double  u20_0, double 
   y00_0);
/* Codes used in model */

/* Flattened Modelica model:

function Modelica.Math.atan3
discrete input Real u1 "First independent variable";
discrete input Real u2 "Second independent variable";
discrete input Real y0(start = 0, unit = "rad", displayUnit = "deg") "y shall be in the range: -pi < y-y0 <= pi";
discrete output Real y(unit = "rad", displayUnit = "deg") "Dependent variable y=atan3(u1, u2, y0)=atan(u1/u2)";
protected 
constant Real pi2 = 6.283185307179586;
discrete Real w;
public 
algorithm 
w := atan2(u1, u2);
if (y0 == 0) then 
y := w;
else
y := w+pi2*integer((3.141592653589793+y0-w)/pi2);
end if;
end Modelica.Math.atan3;

  */
DYMOLA_STATIC double   Modelica_Math_atan3(double  u10_0, double  u20_0, double 
   y00_0) {
  PushContext("Modelica.Math.atan3")
  {
    /* Declare outputs and temporaries */
    double   y0_0;
    double   pi20_0;
    double   w0_0;
    y0_0=0;
    pi20_0 = 6.283185307179586;
    w0_0=0;
    /* Start of real code */
      w0_0 = atan2(u10_0, u20_0);
      if (y00_0 == 0) {
        y0_0 = w0_0;
      }
      else{
        y0_0 = w0_0+pi20_0*real2integer(divGuarded(3.141592653589793+y00_0-w0_0,
          "3.141592653589793+y0-w",pi20_0,"pi2"));
      }
    /* Output section */
    PopContext()
    return y0_0;
  }}
/* DSblock C-code: */

BreakSectionFunctionDef(1)
BreakSectionFunctionDef(0)
#define NX_    6
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    130
#define NP_    60
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1616631659
#define NHash2_ -110692396
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  4
#define NSamp_ 0
#define NCons_ 0
#define NA_    42
#define SizePre_ 0
#define SizeEq_ 10
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 376
#define NGlobalHelpI_ 32
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="KundurSMIB.SMIB";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/aisling/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[13]={4 , 2 , 1 , 2 , 2 , 3 , 4 , 1 , 5 , 1 , 6 , 0
   , 0};
static int QJacobianGrp0[7]={2, 1, 1, 1, 1, 1, 0};
static int QJacobianGrp1[7]={0, 0, 3, 4, 3, 4, 0};
static int QJacobianGrp2[7]={0, 5, 5, 5, 5, 5, 0};
static int QJacobianGrp3[7]={0, 6, 6, 6, 6, 6, 0};
DYMOLA_STATIC struct QJacobianTag_ QJacobianGC2_[5]={
{0, QJacobianGrp0},{0, QJacobianGrp1},{0, QJacobianGrp2},{0, QJacobianGrp3},
  {0,0}};
DYMOLA_STATIC double QJacobianCD_[7]={0  , 44 , 55 , 60 , 70 , 72 , 72};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
memcpy(&DYNX(W_,39), &DymArrays0, sizeof(double)*3);
memcpy(&DYNX(W_,61), &DymArrays1, sizeof(double)*3);
DYNX(W_,84) = 0;
DYNX(W_,4) = 0;
DYNX(W_,5) = 0;
DYNX(W_,13) = 0;
DYNX(W_,12) = 0;
DYNX(W_,20) = 0;
DYNX(W_,21) = 0;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(W_,0) = DYNX(DP_,0);
DYNX(W_,1) = DYNX(DP_,1);
DYNX(W_,8) = DYNX(DP_,0);
DYNX(W_,9) = DYNX(DP_,1);
DYNX(W_,16) = DYNX(DP_,0);
DYNX(W_,17) = DYNX(DP_,1);
DYNX(W_,28) = DYNX(DP_,0);
DYNX(W_,29) = DYNX(DP_,1);
DYNX(W_,30) = sqr(DYNX(DP_,21));
DYNX(W_,31) = DYNX(DP_,22)*DYNX(DP_,22);
DYNX(W_,32) = divGuarded(DYNX(DP_,24)*DYNX(W_,31)*DYNX(W_,28),"transformer.x*(transformer.Vb2old*transformer.Sb)",
  DYNX(W_,30)*DYNX(DP_,20),"transformer.Vb2new*transformer.Sn");
DYNX(W_,33) = divGuarded(DYNX(DP_,25)*DYNX(W_,31)*DYNX(W_,28),"transformer.r*(transformer.Vb2old*transformer.Sb)",
  DYNX(W_,30)*DYNX(DP_,20),"transformer.Vb2new*transformer.Sn");
DYNX(W_,38) = DYNX(DP_,0);
DYNX(W_,46) = DYNX(DP_,28);
DYNX(W_,47) = DYNX(DP_,29);
DYNX(W_,48) = DYNX(DP_,26);
DYNX(W_,49) = DYNX(DP_,27);
DYNX(W_,50) = DYNX(DP_,0);
DYNX(W_,51) = DYNX(DP_,1);
DYNX(W_,60) = DYNX(DP_,0);
DYNX(W_,68) = DYNX(DP_,39);
DYNX(W_,69) = DYNX(DP_,40);
DYNX(W_,70) = DYNX(DP_,37);
DYNX(W_,71) = DYNX(DP_,38);
DYNX(W_,72) = DYNX(DP_,0);
DYNX(W_,73) = 0.899999999997135*DYNX(W_,72);
DYNX(W_,74) = 0.436002238696658*DYNX(W_,72);
DYNX(W_,75) = DYNX(DP_,0);
DYNX(W_,76) = DYNX(DP_,1);
DYNX(W_,77) = DYNX(DP_,42);
DYNX(W_,78) = DYNX(DP_,43);
DYNX(W_,79) = DYNX(DP_,44);
DYNX(W_,80) = DYNX(W_,73);
DYNX(W_,81) = DYNX(W_,74);
DYNX(W_,82) = DYNX(DP_,0);
DYNX(W_,83) = DYNX(DP_,1);
DYNX(W_,95) = 6.283185307179586*DYNX(W_,83);
DYNX(DYNhelp,0) = divinvGuarded(DYNX(DP_,45),"G1.machine.Sn");
DYNX(W_,96) = DYNX(DYNhelp,0)*DYNX(W_,82);
DYNX(W_,97) = divGuarded(DYNX(DP_,45)*DYNX(W_,77),"G1.machine.Sn*G1.machine.V_b",
  DYNX(W_,82)*DYNX(DP_,46),"G1.machine.S_b*G1.machine.Vn");
DYNX(DYNhelp,1) = divinvGuarded(DYNX(W_,77),"G1.machine.V_b");
DYNX(W_,98) = DYNX(DYNhelp,1)*DYNX(DP_,46);
DYNX(W_,99) = divGuarded(DYNX(W_,82)*sqr(DYNX(DP_,46)),"G1.machine.S_b*G1.machine.Vn^2",
  DYNX(DP_,45)*sqr(DYNX(W_,77)),"G1.machine.Sn*G1.machine.V_b^2");
DYNX(DYNhelp,2) = divinvGuarded(DYNX(W_,82),"G1.machine.S_b");
DYNX(W_,100) = DYNX(DYNhelp,2)*DYNX(W_,80);
DYNX(W_,101) = DYNX(DYNhelp,2)*DYNX(W_,81);
DYNX(DYNhelp,3) = cos(0.017453292519943295*DYNX(W_,79));
DYNX(W_,102) = DYNX(W_,78)*DYNX(DYNhelp,3);
DYNX(DYNhelp,4) = sin(0.017453292519943295*DYNX(W_,79));
DYNX(W_,103) = DYNX(W_,78)*DYNX(DYNhelp,4);
DYNX(W_,104) = DYNX(W_,100);
DYNX(W_,105) =  -DYNX(W_,101);
DYNX(W_,106) = divGuarded(DYNX(W_,104)*DYNX(W_,102)-DYNX(W_,105)*DYNX(W_,103),
  "G1.machine.S0.re*G1.machine.Vt0.re-G1.machine.S0.im*G1.machine.Vt0.im",
  DYNX(W_,102)*DYNX(W_,102)+DYNX(W_,103)*DYNX(W_,103),"G1.machine.Vt0.re*G1.machine.Vt0.re+G1.machine.Vt0.im*G1.machine.Vt0.im");
DYNX(W_,107) = divGuarded(DYNX(W_,104)*DYNX(W_,103)+DYNX(W_,105)*DYNX(W_,102),
  "G1.machine.S0.re*G1.machine.Vt0.im+G1.machine.S0.im*G1.machine.Vt0.re",
  DYNX(W_,102)*DYNX(W_,102)+DYNX(W_,103)*DYNX(W_,103),"G1.machine.Vt0.re*G1.machine.Vt0.re+G1.machine.Vt0.im*G1.machine.Vt0.im");
DYNX(W_,108) = DYNX(W_,102);
DYNX(W_,109) = DYNX(W_,103);
DYNX(W_,110) =  -DYNX(W_,106);
DYNX(W_,111) =  -DYNX(W_,107);
DYNX(W_,112) = DYNX(DP_,51);
DYNX(DYNhelp,5) = DYNX(DP_,47)*DYNX(W_,99);
DYNX(DYNhelp,6) = DYNX(W_,112)*DYNX(W_,99);
DYNX(W_,113) = (PushModelContext(1,"Modelica.Math.atan3(G1.machine.Vt0.im+G1.machine.ra*G1.machine.Z_MBtoSB*G1.machine.I0.im+G1.machine.xq0*G1.machine.Z_MBtoSB*G1.machine.I0.re, G1.machine.Vt0.re+G1.machine.ra*G1.machine.Z_MBtoSB*G1.machine.I0.re-G1.machine.xq0*G1.machine.Z_MBtoSB*G1.machine.I0.im, 0)\nModelica.ComplexMath.arg(\nComplex(\nre = G1.machine.Vt0.re+G1.machine.ra*G1.machine.Z_MBtoSB*G1.machine.I0.re-G1.machine.xq0*G1.mac...")
  Modelica_Math_atan3(DYNX(W_,103)+DYNX(DYNhelp,5)*DYNX(W_,107)+DYNX(DYNhelp,6)*
  DYNX(W_,106), DYNX(W_,102)+DYNX(DYNhelp,5)*DYNX(W_,106)-DYNX(DYNhelp,6)*
  DYNX(W_,107), 0));
PopModelContext();
DYNX(DYNhelp,7) = 1.5707963267948966-DYNX(W_,113);
DYNX(DYNhelp,8) = cos(DYNX(DYNhelp,7));
DYNX(DYNhelp,9) = sin(DYNX(DYNhelp,7));
DYNX(DYNhelp,10) = divinvGuarded(DYNX(W_,98),"G1.machine.V_MBtoSB");
DYNX(W_,114) = DYNX(DYNhelp,10)*(DYNX(W_,102)*DYNX(DYNhelp,8)-DYNX(W_,103)*
  DYNX(DYNhelp,9));
DYNX(DYNhelp,11) = 1.5707963267948966-DYNX(W_,113);
DYNX(W_,115) = DYNX(DYNhelp,10)*(DYNX(W_,102)*DYNX(DYNhelp,9)+DYNX(W_,103)*
  DYNX(DYNhelp,8));
DYNX(DYNhelp,12) = 1.5707963267948966-DYNX(W_,113);
DYNX(DYNhelp,13) = divinvGuarded(DYNX(W_,97),"G1.machine.I_MBtoSB");
DYNX(W_,116) = DYNX(DYNhelp,13)*(DYNX(W_,106)*DYNX(DYNhelp,8)-DYNX(W_,107)*
  DYNX(DYNhelp,9));
DYNX(DYNhelp,14) = 1.5707963267948966-DYNX(W_,113);
DYNX(W_,117) = DYNX(DYNhelp,13)*(DYNX(W_,106)*DYNX(DYNhelp,9)+DYNX(W_,107)*
  DYNX(DYNhelp,8));
DYNX(W_,118) = DYNX(W_,114);
DYNX(W_,119) = DYNX(W_,115);
DYNX(W_,120) = DYNX(W_,116);
DYNX(W_,121) = DYNX(W_,117);
DYNX(DYNhelp,15) = divinvGuarded(DYNX(W_,96),"G1.machine.S_SBtoMB");
DYNX(W_,122) = DYNX(DYNhelp,15)*((DYNX(W_,119)+DYNX(DP_,47)*DYNX(W_,121))*
  DYNX(W_,121)+(DYNX(W_,118)+DYNX(DP_,47)*DYNX(W_,120))*DYNX(W_,120));
DYNX(W_,123) = DYNX(W_,119)+DYNX(DP_,47)*DYNX(W_,121)+DYNX(DP_,53)*DYNX(W_,120);
DYNX(W_,124) = DYNX(W_,118)+DYNX(DP_,47)*DYNX(W_,120)-DYNX(DP_,54)*DYNX(W_,121);
DYNX(W_,125) = (DYNX(DP_,51)-DYNX(DP_,52)-divGuarded(DYNX(DP_,58)*DYNX(DP_,54)*(
  DYNX(DP_,51)-DYNX(DP_,52)),"G1.machine.T2q0*G1.machine.x2q*(G1.machine.xq-G1.machine.x1q)",
  DYNX(DP_,56)*DYNX(DP_,52),"G1.machine.T1q0*G1.machine.x1q"))*DYNX(W_,121);
DYNX(W_,126) = DYNX(DP_,50)-DYNX(DP_,48)-divGuarded(DYNX(DP_,57)*DYNX(DP_,53)*(
  DYNX(DP_,50)-DYNX(DP_,48)),"G1.machine.T2d0*G1.machine.x2d*(G1.machine.xd-G1.machine.x1d)",
  DYNX(DP_,55)*DYNX(DP_,48),"G1.machine.T1d0*G1.machine.x1d");
DYNX(W_,127) = DYNX(DP_,48)-DYNX(DP_,53)+divGuarded(DYNX(DP_,57)*DYNX(DP_,53)*(
  DYNX(DP_,50)-DYNX(DP_,48)),"G1.machine.T2d0*G1.machine.x2d*(G1.machine.xd-G1.machine.x1d)",
  DYNX(DP_,55)*DYNX(DP_,48),"G1.machine.T1d0*G1.machine.x1d");
DYNX(DYNhelp,16) = DYNX(W_,126)+DYNX(W_,127);
DYNX(DYNhelp,17) = divinvGuarded(DYNX(DP_,55),"G1.machine.T1d0");
DYNX(W_,128) = DYNX(W_,123)+DYNX(W_,127)*DYNX(W_,120)-DYNX(DYNhelp,17)*
  DYNX(DP_,59)*(DYNX(DYNhelp,16)*DYNX(W_,120)+DYNX(W_,123));
DYNX(DYNhelp,18) = 1-DYNX(DYNhelp,17)*DYNX(DP_,59);
DYNX(W_,129) = divGuarded(DYNX(W_,98)*(DYNX(W_,126)*DYNX(W_,120)+DYNX(W_,128)),
  "G1.machine.V_MBtoSB*(G1.machine.K1*G1.machine.id0+G1.machine.e1q0)",
  DYNX(DYNhelp,18),"1-G1.machine.Taa/G1.machine.T1d0");
BoundParameterConstantSection
DYNX(DYNhelp,19) = divinvGuarded(DYNX(DP_,46),"G1.machine.Vn");
DYNX(W_,94) = DYNX(DYNhelp,19)*DYNX(W_,129)*DYNX(W_,77);
DYNX(DYNhelp,20) = cos(0.005555555555555556*DYNX(DP_,33)*3.141592653589793);
DYNX(W_,18) = DYNX(DP_,32)*DYNX(DYNhelp,20);
DYNX(DYNhelp,21) = sin(0.005555555555555556*DYNX(DP_,33)*3.141592653589793);
DYNX(W_,19) = DYNX(DP_,32)*DYNX(DYNhelp,21);
DYNX(W_,22) = sqrtGuarded(sqr(DYNX(W_,18))+sqr(DYNX(W_,19)),"B3.p.vr^2+B3.p.vi^2");
DYNX(DYNhelp,22) = atan2(DYNX(W_,19), DYNX(W_,18));
DYNX(W_,23) = 0.3183098861837907*DYNX(DYNhelp,22)*180;
BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,2) = DYNX(DP_,3)*cos(0.005555555555555556*DYNX(DP_,4)*3.141592653589793);
DYNX(W_,3) = DYNX(DP_,3)*sin(0.005555555555555556*DYNX(DP_,4)*3.141592653589793);
DYNX(W_,6) = DYNX(DP_,3);
DYNX(W_,7) = DYNX(DP_,4);
DYNX(W_,10) = DYNX(DP_,9)*cos(0.005555555555555556*DYNX(DP_,10)*3.141592653589793);
DYNX(W_,11) = DYNX(DP_,9)*sin(0.005555555555555556*DYNX(DP_,10)*3.141592653589793);
DYNX(W_,14) = DYNX(DP_,9);
DYNX(W_,15) = DYNX(DP_,10);
DYNX(W_,24) =  -DYNX(W_,110);
DYNX(W_,25) =  -DYNX(W_,111);
DYNX(W_,85) = DYNX(W_,78);
DYNX(W_,86) = DYNX(W_,100);
DYNX(W_,87) = DYNX(W_,101);
DYNX(W_,88) = 0.017453292519943295*DYNX(W_,79);
DYNX(W_,89) = DYNX(W_,118);
DYNX(W_,90) = DYNX(W_,119);
DYNX(W_,91) = DYNX(W_,120);
DYNX(W_,92) = DYNX(W_,121);
DYNX(W_,93) = DYNX(W_,122);
DYNX(X_,0) = DYNX(W_,113);
DYNX(X_,2) = DYNX(W_,128);
DYNX(X_,3) = DYNX(W_,125);
DYNX(X_,4) = DYNX(W_,123);
DYNX(X_,5) = DYNX(W_,124);
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
DYNX(F_,0) = 0.0;
DYNX(F_,3) = 0;
DYNX(F_,5) = 0;
DYNX(X_,1) = 1;
DYNX(X_,2) = DYNX(W_,128);
DYNX(X_,4) = DYNX(W_,123);
DYNX(X_,0) = DYNX(W_,113);

 /* Linear system of equations to solve. */
/* Tag: initialization.linear[1] */
/* Introducing 46 common subexpressions used in 110 expressions */
/* Of the common subexpressions 44 are reals, 0 are integers, and 2
   are booleans. */
DYNX(DYNhelp,23) = GreaterEqualTime(1E+60, 0) AND LessTime(1E+60, 1);
DYNX(DYNhelp,24) = cos(DYNX(X_,0));
DYNX(DYNhelp,25) = DYNX(W_,98)*DYNX(DYNhelp,24);
DYNX(DYNhelp,26) = IF DYNX(DYNhelp,23) THEN 0.0 ELSE 1.0+DYNX(W_,48)*DYNX(W_,46)
  -DYNX(W_,49)*DYNX(W_,47);
DYNX(DYNhelp,27) = DYNX(DYNhelp,25)*DYNX(DYNhelp,26);
DYNX(DYNhelp,28) = sin(DYNX(X_,0));
DYNX(DYNhelp,29) = DYNX(W_,98)*DYNX(DYNhelp,28);
DYNX(DYNhelp,30) = IF DYNX(DYNhelp,23) THEN 0.0 ELSE  -(DYNX(W_,48)*DYNX(W_,47)+
  DYNX(W_,49)*DYNX(W_,46));
DYNX(DYNhelp,31) = DYNX(DYNhelp,27)+DYNX(DYNhelp,29)*DYNX(DYNhelp,30);
DYNX(DYNhelp,32) = IF DYNX(DYNhelp,23) THEN 0.0 ELSE DYNX(W_,48)*DYNX(W_,47)+
  DYNX(W_,49)*DYNX(W_,46);
DYNX(DYNhelp,33) = DYNX(DYNhelp,29)*DYNX(DYNhelp,26);
DYNX(DYNhelp,34) = DYNX(DYNhelp,25)*DYNX(DYNhelp,32)+DYNX(DYNhelp,33);
DYNX(DYNhelp,35) = GreaterEqualTime(0.57, 2) AND LessTime(100, 3);
DYNX(DYNhelp,36) = IF DYNX(DYNhelp,35) THEN 0.0 ELSE 1.0+DYNX(W_,70)*DYNX(W_,68)
  -DYNX(W_,71)*DYNX(W_,69);
DYNX(DYNhelp,37) = DYNX(DYNhelp,25)*DYNX(DYNhelp,36);
DYNX(DYNhelp,38) = IF DYNX(DYNhelp,35) THEN 0.0 ELSE  -(DYNX(W_,70)*DYNX(W_,69)+
  DYNX(W_,71)*DYNX(W_,68));
DYNX(DYNhelp,39) = DYNX(DYNhelp,37)+DYNX(DYNhelp,29)*DYNX(DYNhelp,38);
DYNX(DYNhelp,40) = IF DYNX(DYNhelp,35) THEN 0.0 ELSE DYNX(W_,70)*DYNX(W_,69)+
  DYNX(W_,71)*DYNX(W_,68);
DYNX(DYNhelp,41) = DYNX(DYNhelp,29)*DYNX(DYNhelp,36);
DYNX(DYNhelp,42) = DYNX(DYNhelp,25)*DYNX(DYNhelp,40)+DYNX(DYNhelp,41);
/* Automatic tearing of linear system of 18 simultaneous equations
gave a linear system of 6 equations for numerical solution.*/
{
  const char*const varnames_[]={"line_2.p.ir", "line_2.p.ii", "transformer.n.ii",
     "transformer.n.ir", "G1.machine.iq", "G1.machine.id"};
  const double nominal_[]={1, 1, 1, 1, 1, 1};
  DidLinearSystemOfEquations(J, b, y, 6, DYNX(DYNhelp,43), 120, DYNX(did_->helpvari_vec,0), 16);
  /* Jacobian depending on continuous variables */
  SetNeedFactor(J);
  if (NeedFactor(J)) {
    MatrixZeros(J);
    DYNX(DYNhelp,163) = DYNX(W_,97)*DYNX(DYNhelp,24);
    DYNX(DYNhelp,164) = DYNX(W_,33)*DYNX(DYNhelp,163);
    DYNX(DYNhelp,165) = DYNX(W_,97)*DYNX(DYNhelp,28);
    DYNX(DYNhelp,166) = DYNX(W_,32)*DYNX(DYNhelp,165);
    DYNX(DYNhelp,167) = DYNX(W_,32)*DYNX(DYNhelp,163)+DYNX(W_,33)*
      DYNX(DYNhelp,165);
    DYNX(DYNhelp,168) = IF DYNX(DYNhelp,23) THEN 1.0 ELSE  -DYNX(W_,48);
    DYNX(DYNhelp,169) = (-1.0)*DYNX(DYNhelp,168);
    DYNX(DYNhelp,170) = (-1.0)*(IF DYNX(DYNhelp,23) THEN 0.0 ELSE DYNX(W_,49));
    DYNX(DYNhelp,171) = DYNX(DYNhelp,26)*DYNX(W_,32);
    DYNX(DYNhelp,172) = DYNX(DYNhelp,26)*DYNX(W_,33);
    DYNX(DYNhelp,173) = DYNX(DYNhelp,33)-DYNX(DYNhelp,25)*DYNX(DYNhelp,30);
    DYNX(DYNhelp,174) = DYNX(DP_,51)-DYNX(DP_,52);
    DYNX(DYNhelp,175) = divinvGuarded(DYNX(DP_,56),"G1.machine.T1q0");
    DYNX(DYNhelp,176) = divGuarded(DYNX(DYNhelp,175)*DYNX(DP_,58)*DYNX(DP_,54)*
      DYNX(DYNhelp,174),"G1.machine.T2q0*G1.machine.x2q*(G1.machine.xq-G1.machine.x1q)/G1.machine.T1q0",
      DYNX(DP_,52),"G1.machine.x1q");
    DYNX(DYNhelp,177) = DYNX(DYNhelp,174)-DYNX(DYNhelp,176);
    DYNX(DYNhelp,178) = DYNX(DP_,56)*DYNX(DYNhelp,177);
    DYNX(DYNhelp,179) = DYNX(DP_,52)-DYNX(DP_,54)+DYNX(DYNhelp,176);
    DYNX(DYNhelp,180) = DYNX(DP_,58)*DYNX(DYNhelp,179);
    DYNX(DYNhelp,181) = divinvGuarded(DYNX(DP_,58),"G1.machine.T2q0");
    DYNX(DYNhelp,182) = IF DYNX(DYNhelp,23) THEN 0.0 ELSE  -DYNX(W_,49);
    DYNX(DYNhelp,183) = DYNX(DYNhelp,29)*DYNX(DYNhelp,32)-DYNX(DYNhelp,27);
    DYNX(DYNhelp,184) = IF DYNX(DYNhelp,35) THEN 1.0 ELSE  -DYNX(W_,70);
    DYNX(DYNhelp,185) = DYNX(DYNhelp,36)*DYNX(W_,32);
    DYNX(DYNhelp,186) = DYNX(DYNhelp,36)*DYNX(W_,33);
    DYNX(DYNhelp,187) = DYNX(DYNhelp,41)-DYNX(DYNhelp,25)*DYNX(DYNhelp,38);
    DYNX(DYNhelp,188) = DYNX(DYNhelp,29)*DYNX(DYNhelp,40)-DYNX(DYNhelp,37);
    SetMatrixLeading(J, 1, 3, 6,  -DYNX(W_,32));
    SetMatrixLeading(J, 1, 4, 6, DYNX(W_,33));
    SetMatrixLeading(J, 1, 5, 6, DYNX(DYNhelp,164)-DYNX(DYNhelp,166));
    SetMatrixLeading(J, 1, 6, 6, DYNX(DYNhelp,167));
    SetMatrixLeading(J, 2, 3, 6, DYNX(W_,33));
    SetMatrixLeading(J, 2, 4, 6, DYNX(W_,32));
    SetMatrixLeading(J, 2, 5, 6, DYNX(DYNhelp,167));
    SetMatrixLeading(J, 2, 6, 6, DYNX(DYNhelp,166)-DYNX(DYNhelp,164));
    SetMatrixLeading(J, 3, 1, 6, DYNX(DYNhelp,169));
    SetMatrixLeading(J, 3, 2, 6, DYNX(DYNhelp,170));
    SetMatrixLeading(J, 3, 3, 6, DYNX(DYNhelp,170)-DYNX(DYNhelp,171)+
      DYNX(DYNhelp,30)*DYNX(W_,33));
    SetMatrixLeading(J, 3, 4, 6, DYNX(DYNhelp,172)-DYNX(DYNhelp,168)+
      DYNX(DYNhelp,30)*DYNX(W_,32));
    SetMatrixLeading(J, 3, 5, 6, DYNX(DYNhelp,175)*DYNX(DYNhelp,173)*
      DYNX(DYNhelp,178)+DYNX(DYNhelp,181)*DYNX(DYNhelp,173)*DYNX(DYNhelp,180)+
      DYNX(DYNhelp,173)*DYNX(DP_,54)-DYNX(DYNhelp,31)*DYNX(DP_,47));
    SetMatrixLeading(J, 3, 6, 6,  -(DYNX(DYNhelp,173)*DYNX(DP_,47)+
      DYNX(DYNhelp,31)*DYNX(DP_,53)));
    SetMatrixLeading(J, 4, 1, 6, (-1.0)*DYNX(DYNhelp,182));
    SetMatrixLeading(J, 4, 2, 6, DYNX(DYNhelp,169));
    SetMatrixLeading(J, 4, 3, 6, DYNX(DYNhelp,169)-DYNX(DYNhelp,32)*DYNX(W_,32)+
      DYNX(DYNhelp,172));
    SetMatrixLeading(J, 4, 4, 6, DYNX(DYNhelp,32)*DYNX(W_,33)-DYNX(DYNhelp,182)+
      DYNX(DYNhelp,171));
    SetMatrixLeading(J, 4, 5, 6, DYNX(DYNhelp,175)*DYNX(DYNhelp,183)*
      DYNX(DYNhelp,178)+DYNX(DYNhelp,181)*DYNX(DYNhelp,183)*DYNX(DYNhelp,180)+
      DYNX(DYNhelp,183)*DYNX(DP_,54)-DYNX(DYNhelp,34)*DYNX(DP_,47));
    SetMatrixLeading(J, 4, 6, 6,  -(DYNX(DYNhelp,183)*DYNX(DP_,47)+
      DYNX(DYNhelp,34)*DYNX(DP_,53)));
    SetMatrixLeading(J, 5, 1, 6, DYNX(DYNhelp,184));
    SetMatrixLeading(J, 5, 2, 6, IF DYNX(DYNhelp,35) THEN 0.0 ELSE DYNX(W_,71));
    SetMatrixLeading(J, 5, 3, 6, DYNX(DYNhelp,38)*DYNX(W_,33)-DYNX(DYNhelp,185));
    SetMatrixLeading(J, 5, 4, 6, DYNX(DYNhelp,186)+DYNX(DYNhelp,38)*DYNX(W_,32));
    SetMatrixLeading(J, 5, 5, 6, DYNX(DYNhelp,175)*DYNX(DYNhelp,187)*
      DYNX(DYNhelp,178)+DYNX(DYNhelp,181)*DYNX(DYNhelp,187)*DYNX(DYNhelp,180)+
      DYNX(DYNhelp,187)*DYNX(DP_,54)-DYNX(DYNhelp,39)*DYNX(DP_,47));
    SetMatrixLeading(J, 5, 6, 6,  -(DYNX(DYNhelp,187)*DYNX(DP_,47)+
      DYNX(DYNhelp,39)*DYNX(DP_,53)));
    SetMatrixLeading(J, 6, 1, 6, IF DYNX(DYNhelp,35) THEN 0.0 ELSE  -DYNX(W_,71));
    SetMatrixLeading(J, 6, 2, 6, DYNX(DYNhelp,184));
    SetMatrixLeading(J, 6, 3, 6, DYNX(DYNhelp,186)-DYNX(DYNhelp,40)*DYNX(W_,32));
    SetMatrixLeading(J, 6, 4, 6, DYNX(DYNhelp,40)*DYNX(W_,33)+DYNX(DYNhelp,185));
    SetMatrixLeading(J, 6, 5, 6, DYNX(DYNhelp,175)*DYNX(DYNhelp,188)*
      DYNX(DYNhelp,178)+DYNX(DYNhelp,181)*DYNX(DYNhelp,188)*DYNX(DYNhelp,180)+
      DYNX(DYNhelp,188)*DYNX(DP_,54)-DYNX(DYNhelp,42)*DYNX(DP_,47));
    SetMatrixLeading(J, 6, 6, 6,  -(DYNX(DYNhelp,188)*DYNX(DP_,47)+
      DYNX(DYNhelp,42)*DYNX(DP_,53)));
  }
  SetVector(b, 3,  -((IF DYNX(DYNhelp,23) THEN 0.0 ELSE  -DYNX(W_,18))+
    DYNX(DYNhelp,31)*DYNX(X_,4)));
  SetVector(b, 4,  -((IF DYNX(DYNhelp,23) THEN 0.0 ELSE  -DYNX(W_,19))+
    DYNX(DYNhelp,34)*DYNX(X_,4)));
  SetVector(b, 5,  -((IF DYNX(DYNhelp,35) THEN 0.0 ELSE  -DYNX(W_,18))+
    DYNX(DYNhelp,39)*DYNX(X_,4)));
  SetVector(b, 6,  -((IF DYNX(DYNhelp,35) THEN 0.0 ELSE  -DYNX(W_,19))+
    DYNX(DYNhelp,42)*DYNX(X_,4)));
  SetVector(y, 1, 0.0);
  SetVector(y, 2, 0.0);
  SetVector(y, 3, 0.0);
  SetVector(y, 4, 0.0);
  SetVector(y, 5, DYNX(W_,121));
  SetVector(y, 6, DYNX(W_,120));
  SolveLinearSystemOfEquations(J, b, y, 1, "initialization.linear[1]");
  DYNX(W_,56) = GetVector(y, 1);
  DYNX(W_,57) = GetVector(y, 2);
  DYNX(W_,27) = GetVector(y, 3);
  DYNX(W_,26) = GetVector(y, 4);
  DYNX(W_,92) = GetVector(y, 5);
  DYNX(W_,91) = GetVector(y, 6);
  EndStaticLinearSystemOfEquations(J);
}
BreakSectionFunctionCallNew(0);
BreakSectionFunctionEnd()
BreakSectionFunctionStart(1);
DYNX(W_,35) =  -(DYNX(W_,57)+DYNX(W_,27));
DYNX(X_,3) = DYNX(DYNhelp,175)*DYNX(DYNhelp,177)*DYNX(W_,92)*DYNX(DP_,56);
DYNX(X_,5) = DYNX(DYNhelp,181)*(DYNX(X_,3)+DYNX(DYNhelp,179)*DYNX(W_,92))*
  DYNX(DP_,58);
DYNX(W_,89) = DYNX(X_,5)-DYNX(DP_,47)*DYNX(W_,91)+DYNX(DP_,54)*DYNX(W_,92);
DYNX(W_,90) = DYNX(X_,4)-(DYNX(DP_,47)*DYNX(W_,92)+DYNX(DP_,53)*DYNX(W_,91));
DYNX(W_,2) = DYNX(W_,98)*(DYNX(DYNhelp,28)*DYNX(W_,89)+DYNX(DYNhelp,24)*
  DYNX(W_,90));
DYNX(W_,10) = DYNX(W_,33)*DYNX(W_,26)-DYNX(W_,32)*DYNX(W_,27)+DYNX(W_,2);
DYNX(W_,34) =  -(DYNX(W_,56)+DYNX(W_,26));
DYNX(W_,3) = DYNX(W_,98)*(DYNX(DYNhelp,28)*DYNX(W_,90)-DYNX(DYNhelp,24)*
  DYNX(W_,89));
DYNX(W_,11) = DYNX(W_,32)*DYNX(W_,26)+DYNX(W_,33)*DYNX(W_,27)+DYNX(W_,3);
DYNX(W_,25) = DYNX(W_,97)*(DYNX(DYNhelp,28)*DYNX(W_,92)-DYNX(DYNhelp,24)*
  DYNX(W_,91));
DYNX(W_,24) = DYNX(W_,97)*(DYNX(DYNhelp,28)*DYNX(W_,91)+DYNX(DYNhelp,24)*
  DYNX(W_,92));
 /* End of Equation Block */ 

InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection

 /* Linear system of equations to solve. */
/* Tag: simulation.linear[1] */
/* Introducing 45 common subexpressions used in 111 expressions */
/* Of the common subexpressions 43 are reals, 0 are integers, and 2
   are booleans. */
DYNX(DYNhelp,189) = GreaterEqualTime(1E+60, 0) AND LessTime(1E+60, 1);
DYNX(DYNhelp,190) = sin(DYNX(X_,0));
DYNX(DYNhelp,191) = DYNX(W_,98)*DYNX(DYNhelp,190);
DYNX(DYNhelp,192) = IF DYNX(DYNhelp,189) THEN 0.0 ELSE 1.0+DYNX(W_,48)*
  DYNX(W_,46)-DYNX(W_,49)*DYNX(W_,47);
DYNX(DYNhelp,193) = DYNX(DYNhelp,191)*DYNX(DYNhelp,192);
DYNX(DYNhelp,194) = cos(DYNX(X_,0));
DYNX(DYNhelp,195) = DYNX(W_,98)*DYNX(DYNhelp,194);
DYNX(DYNhelp,196) = IF DYNX(DYNhelp,189) THEN 0.0 ELSE  -(DYNX(W_,48)*
  DYNX(W_,47)+DYNX(W_,49)*DYNX(W_,46));
DYNX(DYNhelp,197) = DYNX(DYNhelp,193)-DYNX(DYNhelp,195)*DYNX(DYNhelp,196);
DYNX(DYNhelp,198) = DYNX(DYNhelp,195)*DYNX(DYNhelp,192);
DYNX(DYNhelp,199) = DYNX(DYNhelp,198)+DYNX(DYNhelp,191)*DYNX(DYNhelp,196);
DYNX(DYNhelp,200) = IF DYNX(DYNhelp,189) THEN 0.0 ELSE DYNX(W_,48)*DYNX(W_,47)+
  DYNX(W_,49)*DYNX(W_,46);
DYNX(DYNhelp,201) = DYNX(DYNhelp,191)*DYNX(DYNhelp,200)-DYNX(DYNhelp,198);
DYNX(DYNhelp,202) = DYNX(DYNhelp,195)*DYNX(DYNhelp,200)+DYNX(DYNhelp,193);
DYNX(DYNhelp,203) = GreaterEqualTime(0.57, 2) AND LessTime(100, 3);
DYNX(DYNhelp,204) = IF DYNX(DYNhelp,203) THEN 0.0 ELSE 1.0+DYNX(W_,70)*
  DYNX(W_,68)-DYNX(W_,71)*DYNX(W_,69);
DYNX(DYNhelp,205) = DYNX(DYNhelp,191)*DYNX(DYNhelp,204);
DYNX(DYNhelp,206) = IF DYNX(DYNhelp,203) THEN 0.0 ELSE  -(DYNX(W_,70)*
  DYNX(W_,69)+DYNX(W_,71)*DYNX(W_,68));
DYNX(DYNhelp,207) = DYNX(DYNhelp,205)-DYNX(DYNhelp,195)*DYNX(DYNhelp,206);
DYNX(DYNhelp,208) = DYNX(DYNhelp,195)*DYNX(DYNhelp,204);
DYNX(DYNhelp,209) = DYNX(DYNhelp,208)+DYNX(DYNhelp,191)*DYNX(DYNhelp,206);
DYNX(DYNhelp,210) = IF DYNX(DYNhelp,203) THEN 0.0 ELSE DYNX(W_,70)*DYNX(W_,69)+
  DYNX(W_,71)*DYNX(W_,68);
DYNX(DYNhelp,211) = DYNX(DYNhelp,191)*DYNX(DYNhelp,210)-DYNX(DYNhelp,208);
DYNX(DYNhelp,212) = DYNX(DYNhelp,195)*DYNX(DYNhelp,210)+DYNX(DYNhelp,205);
/* Automatic tearing of linear system of 16 simultaneous equations
gave a linear system of 6 equations for numerical solution.*/
{
  const char*const varnames_[]={"transformer.n.ii", "transformer.n.ir", 
    "line_2.p.ir", "line_2.p.ii", "G1.machine.iq", "G1.machine.id"};
  const double nominal_[]={1, 1, 1, 1, 1, 1};
  DidLinearSystemOfEquations(J, b, y, 6, DYNX(DYNhelp,213), 120, 
    DYNX(did_->helpvari_vec,16), 16);
  /* Jacobian depending on continuous variables */
  SetNeedFactor(J);
  if (NeedFactor(J)) {
    MatrixZeros(J);
    DYNX(DYNhelp,333) = DYNX(W_,97)*DYNX(DYNhelp,194);
    DYNX(DYNhelp,334) = DYNX(W_,33)*DYNX(DYNhelp,333);
    DYNX(DYNhelp,335) = DYNX(W_,97)*DYNX(DYNhelp,190);
    DYNX(DYNhelp,336) = DYNX(W_,32)*DYNX(DYNhelp,335);
    DYNX(DYNhelp,337) = DYNX(W_,33)*DYNX(DYNhelp,335)+DYNX(W_,32)*
      DYNX(DYNhelp,333);
    DYNX(DYNhelp,338) = (-1.0)*(IF DYNX(DYNhelp,189) THEN 0.0 ELSE DYNX(W_,49));
    DYNX(DYNhelp,339) = (-1.0)*(IF DYNX(DYNhelp,189) THEN 1.0 ELSE  -DYNX(W_,48));
    DYNX(DYNhelp,340) = DYNX(W_,33)*DYNX(DYNhelp,192);
    DYNX(DYNhelp,341) = DYNX(DYNhelp,340)+DYNX(W_,32)*DYNX(DYNhelp,196);
    DYNX(DYNhelp,342) = DYNX(W_,32)*DYNX(DYNhelp,192);
    DYNX(DYNhelp,343) = DYNX(DYNhelp,342)-DYNX(W_,33)*DYNX(DYNhelp,196);
    DYNX(DYNhelp,344) = (-1.0)*(IF DYNX(DYNhelp,189) THEN 0.0 ELSE  -DYNX(W_,49));
    DYNX(DYNhelp,345) = DYNX(W_,33)*DYNX(DYNhelp,200)+DYNX(DYNhelp,342);
    DYNX(DYNhelp,346) = DYNX(W_,32)*DYNX(DYNhelp,200)-DYNX(DYNhelp,340);
    DYNX(DYNhelp,347) = IF DYNX(DYNhelp,203) THEN 1.0 ELSE  -DYNX(W_,70);
    DYNX(DYNhelp,348) = DYNX(W_,33)*DYNX(DYNhelp,204);
    DYNX(DYNhelp,349) = DYNX(DYNhelp,348)+DYNX(W_,32)*DYNX(DYNhelp,206);
    DYNX(DYNhelp,350) = DYNX(W_,32)*DYNX(DYNhelp,204);
    DYNX(DYNhelp,351) = DYNX(DYNhelp,350)-DYNX(W_,33)*DYNX(DYNhelp,206);
    DYNX(DYNhelp,352) = DYNX(W_,33)*DYNX(DYNhelp,210)+DYNX(DYNhelp,350);
    DYNX(DYNhelp,353) = DYNX(W_,32)*DYNX(DYNhelp,210)-DYNX(DYNhelp,348);
    SetMatrixLeading(J, 1, 1, 6,  -DYNX(W_,32));
    SetMatrixLeading(J, 1, 2, 6, DYNX(W_,33));
    SetMatrixLeading(J, 1, 5, 6, DYNX(DYNhelp,334)-DYNX(DYNhelp,336));
    SetMatrixLeading(J, 1, 6, 6, DYNX(DYNhelp,337));
    SetMatrixLeading(J, 2, 1, 6, DYNX(W_,33));
    SetMatrixLeading(J, 2, 2, 6, DYNX(W_,32));
    SetMatrixLeading(J, 2, 5, 6, DYNX(DYNhelp,337));
    SetMatrixLeading(J, 2, 6, 6, DYNX(DYNhelp,336)-DYNX(DYNhelp,334));
    SetMatrixLeading(J, 3, 1, 6, DYNX(DYNhelp,338));
    SetMatrixLeading(J, 3, 2, 6, DYNX(DYNhelp,339));
    SetMatrixLeading(J, 3, 3, 6, DYNX(DYNhelp,339));
    SetMatrixLeading(J, 3, 4, 6, DYNX(DYNhelp,338));
    SetMatrixLeading(J, 3, 5, 6, DYNX(DYNhelp,197)*DYNX(DP_,54)-DYNX(DYNhelp,199)
      *DYNX(DP_,47)-DYNX(DYNhelp,341)*DYNX(DYNhelp,333)+DYNX(DYNhelp,343)*
      DYNX(DYNhelp,335));
    SetMatrixLeading(J, 3, 6, 6,  -(DYNX(DYNhelp,197)*DYNX(DP_,47)+
      DYNX(DYNhelp,199)*DYNX(DP_,53)+DYNX(DYNhelp,341)*DYNX(DYNhelp,335)+
      DYNX(DYNhelp,343)*DYNX(DYNhelp,333)));
    SetMatrixLeading(J, 4, 1, 6, DYNX(DYNhelp,339));
    SetMatrixLeading(J, 4, 2, 6, DYNX(DYNhelp,344));
    SetMatrixLeading(J, 4, 3, 6, DYNX(DYNhelp,344));
    SetMatrixLeading(J, 4, 4, 6, DYNX(DYNhelp,339));
    SetMatrixLeading(J, 4, 5, 6, DYNX(DYNhelp,201)*DYNX(DP_,54)-DYNX(DYNhelp,202)
      *DYNX(DP_,47)-DYNX(DYNhelp,345)*DYNX(DYNhelp,333)+DYNX(DYNhelp,346)*
      DYNX(DYNhelp,335));
    SetMatrixLeading(J, 4, 6, 6,  -(DYNX(DYNhelp,201)*DYNX(DP_,47)+
      DYNX(DYNhelp,202)*DYNX(DP_,53)+DYNX(DYNhelp,345)*DYNX(DYNhelp,335)+
      DYNX(DYNhelp,346)*DYNX(DYNhelp,333)));
    SetMatrixLeading(J, 5, 3, 6, DYNX(DYNhelp,347));
    SetMatrixLeading(J, 5, 4, 6, IF DYNX(DYNhelp,203) THEN 0.0 ELSE DYNX(W_,71));
    SetMatrixLeading(J, 5, 5, 6, DYNX(DYNhelp,207)*DYNX(DP_,54)-DYNX(DYNhelp,209)
      *DYNX(DP_,47)-DYNX(DYNhelp,349)*DYNX(DYNhelp,333)+DYNX(DYNhelp,351)*
      DYNX(DYNhelp,335));
    SetMatrixLeading(J, 5, 6, 6,  -(DYNX(DYNhelp,207)*DYNX(DP_,47)+
      DYNX(DYNhelp,209)*DYNX(DP_,53)+DYNX(DYNhelp,349)*DYNX(DYNhelp,335)+
      DYNX(DYNhelp,351)*DYNX(DYNhelp,333)));
    SetMatrixLeading(J, 6, 3, 6, IF DYNX(DYNhelp,203) THEN 0.0 ELSE  -
      DYNX(W_,71));
    SetMatrixLeading(J, 6, 4, 6, DYNX(DYNhelp,347));
    SetMatrixLeading(J, 6, 5, 6, DYNX(DYNhelp,211)*DYNX(DP_,54)-DYNX(DYNhelp,212)
      *DYNX(DP_,47)-DYNX(DYNhelp,352)*DYNX(DYNhelp,333)+DYNX(DYNhelp,353)*
      DYNX(DYNhelp,335));
    SetMatrixLeading(J, 6, 6, 6,  -(DYNX(DYNhelp,211)*DYNX(DP_,47)+
      DYNX(DYNhelp,212)*DYNX(DP_,53)+DYNX(DYNhelp,352)*DYNX(DYNhelp,335)+
      DYNX(DYNhelp,353)*DYNX(DYNhelp,333)));
  }
  SetVector(b, 3,  -((IF DYNX(DYNhelp,189) THEN 0.0 ELSE  -DYNX(W_,18))+
    DYNX(DYNhelp,197)*DYNX(X_,5)+DYNX(DYNhelp,199)*DYNX(X_,4)));
  SetVector(b, 4,  -((IF DYNX(DYNhelp,189) THEN 0.0 ELSE  -DYNX(W_,19))+
    DYNX(DYNhelp,201)*DYNX(X_,5)+DYNX(DYNhelp,202)*DYNX(X_,4)));
  SetVector(b, 5,  -((IF DYNX(DYNhelp,203) THEN 0.0 ELSE  -DYNX(W_,18))+
    DYNX(DYNhelp,207)*DYNX(X_,5)+DYNX(DYNhelp,209)*DYNX(X_,4)));
  SetVector(b, 6,  -((IF DYNX(DYNhelp,203) THEN 0.0 ELSE  -DYNX(W_,19))+
    DYNX(DYNhelp,211)*DYNX(X_,5)+DYNX(DYNhelp,212)*DYNX(X_,4)));
  SetVector(y, 1, RememberSimple_(DYNX(W_,27), 0));
  SetVector(y, 2, RememberSimple_(DYNX(W_,26), 1));
  SetVector(y, 3, RememberSimple_(DYNX(W_,56), 2));
  SetVector(y, 4, RememberSimple_(DYNX(W_,57), 3));
  SetVector(y, 5, RememberSimple_(DYNX(W_,92), 4));
  SetVector(y, 6, RememberSimple_(DYNX(W_,91), 5));
  SolveLinearSystemOfEquations(J, b, y, 1, "simulation.linear[1]");
  DYNX(W_,27) = GetVector(y, 1);
  DYNX(W_,26) = GetVector(y, 2);
  DYNX(W_,56) = GetVector(y, 3);
  DYNX(W_,57) = GetVector(y, 4);
  DYNX(W_,92) = GetVector(y, 5);
  DYNX(W_,91) = GetVector(y, 6);
  EndStaticLinearSystemOfEquations(J);
}
DYNX(W_,89) = DYNX(X_,5)-DYNX(DP_,47)*DYNX(W_,91)+DYNX(DP_,54)*DYNX(W_,92);
DYNX(W_,90) = DYNX(X_,4)-(DYNX(DP_,47)*DYNX(W_,92)+DYNX(DP_,53)*DYNX(W_,91));
DYNX(W_,2) = DYNX(W_,98)*(DYNX(DYNhelp,190)*DYNX(W_,89)+DYNX(DYNhelp,194)*
  DYNX(W_,90));
DYNX(W_,34) =  -(DYNX(W_,56)+DYNX(W_,26));
DYNX(W_,24) = DYNX(W_,97)*(DYNX(DYNhelp,190)*DYNX(W_,91)+DYNX(DYNhelp,194)*
  DYNX(W_,92));
DYNX(W_,25) = DYNX(W_,97)*(DYNX(DYNhelp,190)*DYNX(W_,92)-DYNX(DYNhelp,194)*
  DYNX(W_,91));
DYNX(W_,10) = DYNX(W_,2)-DYNX(W_,33)*DYNX(W_,24)+DYNX(W_,32)*DYNX(W_,25);
DYNX(W_,35) =  -(DYNX(W_,57)+DYNX(W_,27));
DYNX(W_,3) = DYNX(W_,98)*(DYNX(DYNhelp,190)*DYNX(W_,90)-DYNX(DYNhelp,194)*
  DYNX(W_,89));
DYNX(W_,11) = DYNX(W_,3)-(DYNX(W_,33)*DYNX(W_,25)+DYNX(W_,32)*DYNX(W_,24));
 /* End of Equation Block */ 

DYNX(DYNhelp,354) = DYNX(DYNhelp,17)*DYNX(DP_,59);
DYNX(DYNhelp,355) = DYNX(DP_,50)-DYNX(DP_,48);
if (NewParameters_) {
DYNX(DYNhelp,356) = divinvGuarded(DYNX(DP_,48),"G1.machine.x1d");
}
DYNX(DYNhelp,357) = DYNX(DYNhelp,356)*DYNX(DYNhelp,17)*DYNX(DP_,57)*DYNX(DP_,53)
  *DYNX(DYNhelp,355);
DYNX(F_,2) = DYNX(DYNhelp,17)*((1-DYNX(DYNhelp,354))*DYNX(W_,94)-(DYNX(X_,2)+(
  DYNX(DYNhelp,355)-DYNX(DYNhelp,357))*DYNX(W_,91)));
DYNX(DYNhelp,358) = DYNX(DP_,48)-DYNX(DP_,53);
DYNX(DYNhelp,359) = DYNX(DYNhelp,356)*DYNX(DYNhelp,17)*DYNX(DP_,57)*DYNX(DP_,53)
  *(DYNX(DP_,50)-DYNX(DP_,48));
if (NewParameters_) {
DYNX(DYNhelp,360) = divinvGuarded(DYNX(DP_,57),"G1.machine.T2d0");
}
DYNX(F_,4) = DYNX(DYNhelp,360)*(DYNX(X_,2)-DYNX(X_,4)-(DYNX(DYNhelp,358)+
  DYNX(DYNhelp,359))*DYNX(W_,91)+DYNX(DYNhelp,17)*DYNX(DP_,59)*DYNX(W_,94));
DYNX(W_,93) = (DYNX(W_,90)+DYNX(DP_,47)*DYNX(W_,92))*DYNX(W_,92)+(DYNX(W_,89)+
  DYNX(DP_,47)*DYNX(W_,91))*DYNX(W_,91);
if (NewParameters_) {
DYNX(DYNhelp,361) = divinvGuarded(DYNX(DP_,49),"G1.machine.M");
}
DYNX(F_,1) = DYNX(DYNhelp,361)*(DYNX(W_,122)*DYNX(W_,96)-DYNX(W_,93));
DYNX(F_,0) = DYNX(W_,95)*(DYNX(X_,1)-1);
DYNX(DYNhelp,362) = DYNX(DP_,51)-DYNX(DP_,52);
if (NewParameters_) {
DYNX(DYNhelp,363) = divinvGuarded(DYNX(DP_,56),"G1.machine.T1q0");
}
DYNX(DYNhelp,364) = DYNX(DYNhelp,363)*DYNX(DP_,58)*DYNX(DP_,54)*DYNX(DYNhelp,362);
if (NewParameters_) {
DYNX(DYNhelp,365) = divinvGuarded(DYNX(DP_,52),"G1.machine.x1q");
}
DYNX(DYNhelp,366) = DYNX(DYNhelp,365)*DYNX(DYNhelp,364);
DYNX(F_,3) = DYNX(DYNhelp,363)*((DYNX(DYNhelp,362)-DYNX(DYNhelp,366))*
  DYNX(W_,92)-DYNX(X_,3));
DYNX(DYNhelp,367) = DYNX(DYNhelp,363)*DYNX(DP_,58)*DYNX(DP_,54)*(DYNX(DP_,51)-
  DYNX(DP_,52));
DYNX(DYNhelp,368) = DYNX(DYNhelp,365)*DYNX(DYNhelp,367);
if (NewParameters_) {
DYNX(DYNhelp,369) = divinvGuarded(DYNX(DP_,58),"G1.machine.T2q0");
}
DYNX(F_,5) = DYNX(DYNhelp,369)*(DYNX(X_,3)-DYNX(X_,5)+(DYNX(DP_,52)-DYNX(DP_,54)
  +DYNX(DYNhelp,368))*DYNX(W_,92));

AcceptedSection1

AcceptedSection2
DYNX(W_,6) = sqrtGuarded(sqr(DYNX(W_,2))+sqr(DYNX(W_,3)),"B1.p.vr^2+B1.p.vi^2");
DYNX(DYNhelp,370) = atan2(DYNX(W_,3), DYNX(W_,2));
DYNX(W_,7) = 0.3183098861837907*DYNX(DYNhelp,370)*180;
DYNX(W_,14) = sqrtGuarded(sqr(DYNX(W_,10))+sqr(DYNX(W_,11)),"B2.p.vr^2+B2.p.vi^2");
DYNX(DYNhelp,371) = atan2(DYNX(W_,11), DYNX(W_,10));
DYNX(W_,15) = 0.3183098861837907*DYNX(DYNhelp,371)*180;

 /* Linear system of equations to solve. */
/* Tag: simulation.linear[2] */
/* Introducing 2 common subexpressions used in 5 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 1
   are booleans. */
DYNX(DYNhelp,372) = GreaterEqualTime(1E+60, 0) AND LessTime(1E+60, 1);
DYNX(DYNhelp,373) = IF DYNX(DYNhelp,372) THEN 1.0 ELSE  -DYNX(W_,48);
{
const char*const varnames_[]={"line_1.n.ii", "line_1.n.ir"};
const double nominal_[]={1, 1};
DYNX(W_,37)=RememberSimple_(DYNX(W_,37), 6);
DYNX(W_,36)=RememberSimple_(DYNX(W_,36), 7);
SolveLinear2by2(IF DYNX(DYNhelp,372) THEN 0.0 ELSE DYNX(W_,49), DYNX(DYNhelp,373),
   
DYNX(DYNhelp,373), IF DYNX(DYNhelp,372) THEN 0.0 ELSE  -DYNX(W_,49), 
 -(IF DYNX(DYNhelp,372) THEN 0.0 ELSE DYNX(W_,18)-DYNX(W_,10)-DYNX(W_,48)*(
  DYNX(W_,19)*DYNX(W_,47)-DYNX(W_,18)*DYNX(W_,46))-DYNX(W_,49)*(DYNX(W_,18)*
  DYNX(W_,47)+DYNX(W_,19)*DYNX(W_,46))),  -(IF DYNX(DYNhelp,372) THEN 0.0 ELSE 
  DYNX(W_,19)-DYNX(W_,11)-DYNX(W_,49)*(DYNX(W_,19)*DYNX(W_,47)-DYNX(W_,18)*
  DYNX(W_,46))+DYNX(W_,48)*(DYNX(W_,18)*DYNX(W_,47)+DYNX(W_,19)*DYNX(W_,46))), &
  DYNX(W_,37), &DYNX(W_,36), 
varnames_, (DSE_STRUCT QiErr), "simulation.linear[2]");
if (*(DSE_STRUCT QiErr)!=0) {goto leave;}
}
 /* End of Equation Block */ 

DYNX(W_,42) = (DYNX(W_,10)*DYNX(W_,34)+DYNX(W_,11)*DYNX(W_,35))*DYNX(W_,38);
DYNX(W_,43) =  -(DYNX(W_,18)*DYNX(W_,36)+DYNX(W_,19)*DYNX(W_,37))*DYNX(W_,38);
DYNX(W_,44) = (DYNX(W_,11)*DYNX(W_,34)-DYNX(W_,10)*DYNX(W_,35))*DYNX(W_,38);
DYNX(W_,45) =  -(DYNX(W_,19)*DYNX(W_,36)-DYNX(W_,18)*DYNX(W_,37))*DYNX(W_,38);

 /* Linear system of equations to solve. */
/* Tag: simulation.linear[3] */
/* Introducing 2 common subexpressions used in 5 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 1
   are booleans. */
DYNX(DYNhelp,374) = GreaterEqualTime(0.57, 2) AND LessTime(100, 3);
DYNX(DYNhelp,375) = IF DYNX(DYNhelp,374) THEN 1.0 ELSE  -DYNX(W_,70);
{
const char*const varnames_[]={"line_2.n.ii", "line_2.n.ir"};
const double nominal_[]={1, 1};
DYNX(W_,59)=RememberSimple_(DYNX(W_,59), 8);
DYNX(W_,58)=RememberSimple_(DYNX(W_,58), 9);
SolveLinear2by2(IF DYNX(DYNhelp,374) THEN 0.0 ELSE DYNX(W_,71), DYNX(DYNhelp,375),
   
DYNX(DYNhelp,375), IF DYNX(DYNhelp,374) THEN 0.0 ELSE  -DYNX(W_,71), 
 -(IF DYNX(DYNhelp,374) THEN 0.0 ELSE DYNX(W_,18)-DYNX(W_,10)-DYNX(W_,70)*(
  DYNX(W_,19)*DYNX(W_,69)-DYNX(W_,18)*DYNX(W_,68))-DYNX(W_,71)*(DYNX(W_,18)*
  DYNX(W_,69)+DYNX(W_,19)*DYNX(W_,68))),  -(IF DYNX(DYNhelp,374) THEN 0.0 ELSE 
  DYNX(W_,19)-DYNX(W_,11)-DYNX(W_,71)*(DYNX(W_,19)*DYNX(W_,69)-DYNX(W_,18)*
  DYNX(W_,68))+DYNX(W_,70)*(DYNX(W_,18)*DYNX(W_,69)+DYNX(W_,19)*DYNX(W_,68))), &
  DYNX(W_,59), &DYNX(W_,58), 
varnames_, (DSE_STRUCT QiErr), "simulation.linear[3]");
if (*(DSE_STRUCT QiErr)!=0) {goto leave;}
}
 /* End of Equation Block */ 

DYNX(W_,54) =  -(DYNX(W_,36)+DYNX(W_,58));
DYNX(W_,55) =  -(DYNX(W_,37)+DYNX(W_,59));
DYNX(W_,52) =  -(DYNX(W_,18)*DYNX(W_,54)+DYNX(W_,19)*DYNX(W_,55))*DYNX(W_,50);
DYNX(W_,53) =  -(DYNX(W_,18)*DYNX(W_,55)-DYNX(W_,19)*DYNX(W_,54))*DYNX(W_,50);
DYNX(W_,64) = (DYNX(W_,10)*DYNX(W_,56)+DYNX(W_,11)*DYNX(W_,57))*DYNX(W_,60);
DYNX(W_,65) =  -(DYNX(W_,18)*DYNX(W_,58)+DYNX(W_,19)*DYNX(W_,59))*DYNX(W_,60);
DYNX(W_,66) = (DYNX(W_,11)*DYNX(W_,56)-DYNX(W_,10)*DYNX(W_,57))*DYNX(W_,60);
DYNX(W_,67) =  -(DYNX(W_,19)*DYNX(W_,58)-DYNX(W_,18)*DYNX(W_,59))*DYNX(W_,60);
DYNX(W_,85) = DYNX(W_,6);
DYNX(W_,86) = DYNX(W_,2)*DYNX(W_,24)+DYNX(W_,3)*DYNX(W_,25);
DYNX(W_,87) = DYNX(W_,3)*DYNX(W_,24)-DYNX(W_,2)*DYNX(W_,25);
DYNX(W_,88) = DYNX(DYNhelp,370);

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("SysData.S_b", "System base [MVA]", 0, 2220, 0.0,0.0,0.0,0,560)
DeclareParameter("SysData.fn", "System Frequency [Hz]", 1, 60, 0.0,0.0,0.0,0,560)
DeclareParameter("B1.V_b", "Base voltage of the bus [kV]", 2, 400, 0.0,0.0,0.0,0,560)
DeclareParameter("B1.V_0", "Voltage magnitude (pu) [1]", 3, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("B1.angle_0", "Voltage angle [deg]", 4, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("B1.P_0", "Active power [MW]", 5, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("B1.Q_0", "Reactive power [Mvar]", 6, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("B1.S_b", "System base power [MVA]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("B1.fn", "System Frequeny [Hz]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("B1.p.vr", "Real part of the voltage [1]", 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("B1.p.vi", "Imaginary part of the voltage [1]", 0.0, 0.0,0.0,0.0,\
0,520)
DeclareVariable("B1.p.ir", "Real part of the current [1]", 0, 0.0,0.0,0.0,0,777)
DeclareVariable("B1.p.ii", "Imaginary part of the current [1]", 0, 0.0,0.0,0.0,0,777)
DeclareVariable("B1.V", "Bus voltage magnitude (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("B1.angle", "Bus voltage angle [deg]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("B1.displayPF", "Display voltage values: [:#(type=Boolean)]", 7,\
 true, 0.0,0.0,0.0,0,562)
DeclareParameter("B2.V_b", "Base voltage of the bus [kV]", 8, 400, 0.0,0.0,0.0,0,560)
DeclareParameter("B2.V_0", "Voltage magnitude (pu) [1]", 9, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("B2.angle_0", "Voltage angle [deg]", 10, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("B2.P_0", "Active power [MW]", 11, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("B2.Q_0", "Reactive power [Mvar]", 12, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("B2.S_b", "System base power [MVA]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("B2.fn", "System Frequeny [Hz]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("B2.p.vr", "Real part of the voltage [1]", 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("B2.p.vi", "Imaginary part of the voltage [1]", 0.0, 0.0,0.0,0.0,\
0,520)
DeclareVariable("B2.p.ir", "Real part of the current", 0, 0.0,0.0,0.0,0,777)
DeclareVariable("B2.p.ii", "Imaginary part of the current", 0, 0.0,0.0,0.0,0,777)
DeclareVariable("B2.V", "Bus voltage magnitude (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("B2.angle", "Bus voltage angle [deg]", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("B2.displayPF", "Display voltage values: [:#(type=Boolean)]", 13,\
 true, 0.0,0.0,0.0,0,562)
DeclareParameter("B3.V_b", "Base voltage of the bus [kV]", 14, 400, 0.0,0.0,0.0,\
0,560)
DeclareParameter("B3.V_0", "Voltage magnitude (pu) [1]", 15, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("B3.angle_0", "Voltage angle [deg]", 16, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("B3.P_0", "Active power [MW]", 17, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("B3.Q_0", "Reactive power [Mvar]", 18, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("B3.S_b", "System base power [MVA]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("B3.fn", "System Frequeny [Hz]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("B3.p.vr", "Real part of the voltage", 0.0, 0.0,0.0,0.0,0,521)
DeclareVariable("B3.p.vi", "Imaginary part of the voltage", 0.0, 0.0,0.0,0.0,0,521)
DeclareVariable("B3.p.ir", "Real part of the current", 0, 0.0,0.0,0.0,0,777)
DeclareVariable("B3.p.ii", "Imaginary part of the current", 0, 0.0,0.0,0.0,0,777)
DeclareVariable("B3.V", "Bus voltage magnitude (pu) [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("B3.angle", "Bus voltage angle [deg]", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("B3.displayPF", "Display voltage values: [:#(type=Boolean)]", 19,\
 true, 0.0,0.0,0.0,0,562)
DeclareAlias2("transformer.p.vr", "Real part of the voltage [1]", "B1.p.vr", 1, 5,\
 2, 4)
DeclareAlias2("transformer.p.vi", "Imaginary part of the voltage [1]", "B1.p.vi", 1,\
 5, 3, 4)
DeclareVariable("transformer.p.ir", "Real part of the current [1]", 0.0, \
0.0,0.0,0.0,0,776)
DeclareVariable("transformer.p.ii", "Imaginary part of the current [1]", 0.0, \
0.0,0.0,0.0,0,776)
DeclareAlias2("transformer.n.vr", "Real part of the voltage [1]", "B2.p.vr", 1, 5,\
 10, 4)
DeclareAlias2("transformer.n.vi", "Imaginary part of the voltage [1]", "B2.p.vi", 1,\
 5, 11, 4)
DeclareVariable("transformer.n.ir", "Real part of the current", 0.0, 0.0,0.0,0.0,\
0,776)
DeclareVariable("transformer.n.ii", "Imaginary part of the current", 0.0, \
0.0,0.0,0.0,0,776)
DeclareVariable("transformer.Sb", "System base power (MVA) [MVA]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareParameter("transformer.Sn", "Power rating (MVA)", 20, 2220, 0.0,0.0,0.0,0,560)
DeclareParameter("transformer.V_b", "Sending end bus voltage (kV)", 21, 400, \
0.0,0.0,0.0,0,560)
DeclareParameter("transformer.Vn", "Voltage rating (kV)", 22, 400, 0.0,0.0,0.0,0,560)
DeclareVariable("transformer.fn", "Frequency rating (Hz) [Hz]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareParameter("transformer.kT", "Nominal tap ratio (kV1/kV2)", 23, 1, \
0.0,0.0,0.0,0,560)
DeclareParameter("transformer.x", "Reactance (pu machine base)", 24, 0.15, \
0.0,0.0,0.0,0,560)
DeclareParameter("transformer.r", "Resistance (pu machine base)", 25, 0, \
0.0,0.0,0.0,0,560)
DeclareVariable("transformer.Vb2new", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("transformer.Vb2old", "", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("transformer.xT", "Reactance, p.u system base", 0.0, 0.0,0.0,0.0,\
0,2561)
DeclareVariable("transformer.rT", "Resistance, p.u system base", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareAlias2("line_1.p.vr", "Real part of the voltage [1]", "B2.p.vr", 1, 5, 10,\
 4)
DeclareAlias2("line_1.p.vi", "Imaginary part of the voltage [1]", "B2.p.vi", 1, 5,\
 11, 4)
DeclareVariable("line_1.p.ir", "Real part of the current", 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("line_1.p.ii", "Imaginary part of the current", 0.0, 0.0,0.0,0.0,\
0,776)
DeclareAlias2("line_1.n.vr", "Real part of the voltage", "B3.p.vr", 1, 5, 18, 4)
DeclareAlias2("line_1.n.vi", "Imaginary part of the voltage", "B3.p.vi", 1, 5, 19,\
 4)
DeclareVariable("line_1.n.ir", "Real part of the current", 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("line_1.n.ii", "Imaginary part of the current", 0.0, 0.0,0.0,0.0,\
0,776)
DeclareParameter("line_1.R", "Resistance (pu) [1]", 26, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("line_1.X", "Reactance (pu) [1]", 27, 0.5, 0.0,0.0,0.0,0,560)
DeclareParameter("line_1.G", "Shunt half conductance (pu) [1]", 28, 0, 0.0,0.0,\
0.0,0,560)
DeclareParameter("line_1.B", "Shunt half susceptance (pu) [1]", 29, 0, 0.0,0.0,\
0.0,0,560)
DeclareVariable("line_1.S_b", "System base power (MVA) [MVA]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("line_1.t1", "[s]", 1E+60, 0.0,0.0,0.0,0,513)
DeclareVariable("line_1.t2", "[s]", 1E+60, 0.0,0.0,0.0,0,513)
DeclareVariable("line_1.opening", "[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,517)
DeclareParameter("line_1.displayPF", "Display power flow results: [:#(type=Boolean)]",\
 30, false, 0.0,0.0,0.0,0,562)
DeclareVariable("line_1.P12", "[MW]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("line_1.P21", "[MW]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("line_1.Q12", "[Mvar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("line_1.Q21", "[Mvar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("line_1.vs.re", "Real part of complex number [1]", "B2.p.vr", 1, 5,\
 10, 0)
DeclareAlias2("line_1.vs.im", "Imaginary part of complex number [1]", "B2.p.vi", 1,\
 5, 11, 0)
DeclareAlias2("line_1.is.re", "Real part of complex number", "line_1.p.ir", 1, 5,\
 34, 0)
DeclareAlias2("line_1.is.im", "Imaginary part of complex number", "line_1.p.ii", 1,\
 5, 35, 0)
DeclareAlias2("line_1.vr.re", "Real part of complex number", "B3.p.vr", 1, 5, 18,\
 0)
DeclareAlias2("line_1.vr.im", "Imaginary part of complex number", "B3.p.vi", 1, 5,\
 19, 0)
DeclareAlias2("line_1.ir.re", "Real part of complex number", "line_1.n.ir", 1, 5,\
 36, 0)
DeclareAlias2("line_1.ir.im", "Imaginary part of complex number", "line_1.n.ii", 1,\
 5, 37, 0)
DeclareVariable("line_1.Y.re", "Real part of complex number [1]", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("line_1.Y.im", "Imaginary part of complex number [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("line_1.Z.re", "Real part of complex number [1]", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("line_1.Z.im", "Imaginary part of complex number [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareParameter("infinite_bus.V_b", "Base voltage of the bus [kV]", 31, 400, \
0.0,0.0,0.0,0,560)
DeclareParameter("infinite_bus.V_0", "Voltage magnitude (pu) [1]", 32, 0.90081, \
0.0,0.0,0.0,0,560)
DeclareParameter("infinite_bus.angle_0", "Voltage angle [deg]", 33, 0, 0.0,0.0,\
0.0,0,560)
DeclareParameter("infinite_bus.P_0", "Active power [MW]", 34, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("infinite_bus.Q_0", "Reactive power [Mvar]", 35, 0, 0.0,0.0,0.0,\
0,560)
DeclareVariable("infinite_bus.S_b", "System base power [MVA]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("infinite_bus.fn", "System Frequeny [Hz]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("infinite_bus.P", "Active Power absorbed by the Infinite bus (MW)",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("infinite_bus.Q", "Reactive Power absorbed by the Infinite bus (MVAr)",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("infinite_bus.p.vr", "Real part of the voltage", "B3.p.vr", 1, 5, 18,\
 4)
DeclareAlias2("infinite_bus.p.vi", "Imaginary part of the voltage", "B3.p.vi", 1,\
 5, 19, 4)
DeclareVariable("infinite_bus.p.ir", "Real part of the current", 0.0, 0.0,0.0,\
0.0,0,776)
DeclareVariable("infinite_bus.p.ii", "Imaginary part of the current", 0.0, \
0.0,0.0,0.0,0,776)
DeclareParameter("infinite_bus.displayPF", "Display power flow results: [:#(type=Boolean)]",\
 36, false, 0.0,0.0,0.0,0,562)
DeclareAlias2("line_2.p.vr", "Real part of the voltage [1]", "B2.p.vr", 1, 5, 10,\
 4)
DeclareAlias2("line_2.p.vi", "Imaginary part of the voltage [1]", "B2.p.vi", 1, 5,\
 11, 4)
DeclareVariable("line_2.p.ir", "Real part of the current", 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("line_2.p.ii", "Imaginary part of the current", 0.0, 0.0,0.0,0.0,\
0,776)
DeclareAlias2("line_2.n.vr", "Real part of the voltage", "B3.p.vr", 1, 5, 18, 4)
DeclareAlias2("line_2.n.vi", "Imaginary part of the voltage", "B3.p.vi", 1, 5, 19,\
 4)
DeclareVariable("line_2.n.ir", "Real part of the current", 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("line_2.n.ii", "Imaginary part of the current", 0.0, 0.0,0.0,0.0,\
0,776)
DeclareParameter("line_2.R", "Resistance (pu) [1]", 37, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("line_2.X", "Reactance (pu) [1]", 38, 0.93, 0.0,0.0,0.0,0,560)
DeclareParameter("line_2.G", "Shunt half conductance (pu) [1]", 39, 0, 0.0,0.0,\
0.0,0,560)
DeclareParameter("line_2.B", "Shunt half susceptance (pu) [1]", 40, 0, 0.0,0.0,\
0.0,0,560)
DeclareVariable("line_2.S_b", "System base power (MVA) [MVA]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("line_2.t1", "[s]", 0.57, 0.0,0.0,0.0,0,513)
DeclareVariable("line_2.t2", "[s]", 100, 0.0,0.0,0.0,0,513)
DeclareVariable("line_2.opening", "[:#(type=Integer)]", 1, 0.0,0.0,0.0,0,517)
DeclareParameter("line_2.displayPF", "Display power flow results: [:#(type=Boolean)]",\
 41, false, 0.0,0.0,0.0,0,562)
DeclareVariable("line_2.P12", "[MW]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("line_2.P21", "[MW]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("line_2.Q12", "[Mvar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("line_2.Q21", "[Mvar]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("line_2.vs.re", "Real part of complex number [1]", "B2.p.vr", 1, 5,\
 10, 0)
DeclareAlias2("line_2.vs.im", "Imaginary part of complex number [1]", "B2.p.vi", 1,\
 5, 11, 0)
DeclareAlias2("line_2.is.re", "Real part of complex number", "line_2.p.ir", 1, 5,\
 56, 0)
DeclareAlias2("line_2.is.im", "Imaginary part of complex number", "line_2.p.ii", 1,\
 5, 57, 0)
DeclareAlias2("line_2.vr.re", "Real part of complex number", "B3.p.vr", 1, 5, 18,\
 0)
DeclareAlias2("line_2.vr.im", "Imaginary part of complex number", "B3.p.vi", 1, 5,\
 19, 0)
DeclareAlias2("line_2.ir.re", "Real part of complex number", "line_2.n.ir", 1, 5,\
 58, 0)
DeclareAlias2("line_2.ir.im", "Imaginary part of complex number", "line_2.n.ii", 1,\
 5, 59, 0)
DeclareVariable("line_2.Y.re", "Real part of complex number [1]", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("line_2.Y.im", "Imaginary part of complex number [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("line_2.Z.re", "Real part of complex number [1]", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("line_2.Z.im", "Imaginary part of complex number [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("S_b", "[MVA]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareParameter("G1.V_b", "Base voltage of the bus [kV]", 42, 400, 0.0,0.0,0.0,\
0,560)
DeclareParameter("G1.V_0", "Voltage magnitude (pu) [1]", 43, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("G1.angle_0", "Voltage angle [deg]", 44, 28.34291446292462, \
0.0,0.0,0.0,0,560)
DeclareVariable("G1.P_0", "Active power [MW]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("G1.Q_0", "Reactive power [Mvar]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("G1.S_b", "System base power [MVA]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("G1.fn", "System Frequeny [Hz]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("G1.machine.V_b", "Base voltage of the bus [kV]", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("G1.machine.V_0", "Voltage magnitude (pu) [1]", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("G1.machine.angle_0", "Voltage angle [deg]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("G1.machine.P_0", "Active power [MW]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("G1.machine.Q_0", "Reactive power [Mvar]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("G1.machine.S_b", "System base power [MVA]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("G1.machine.fn", "System Frequeny [Hz]", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("G1.machine.Sn", "Power rating (MVA) [MVA]", 45, 2220, 0.0,0.0,\
0.0,0,560)
DeclareParameter("G1.machine.Vn", "Voltage rating (kV) [kV]", 46, 400, 0.0,0.0,\
0.0,0,560)
DeclareParameter("G1.machine.ra", "Armature resistance (pu) [1]", 47, 0.003, \
0.0,0.0,0.0,0,560)
DeclareParameter("G1.machine.x1d", "d-axis transient reactance (pu) [1]", 48, \
0.3, 0.0,0.0,0.0,0,560)
DeclareParameter("G1.machine.M", "Mechanical starting time (2H), kWs/kVA", 49, 7,\
 0.0,0.0,0.0,0,560)
DeclareVariable("G1.machine.D", "Damping coefficient", 0, 0.0,0.0,0.0,0,513)
DeclareAlias2("G1.machine.p.vr", "Real part of the voltage [1]", "B1.p.vr", 1, 5,\
 2, 4)
DeclareAlias2("G1.machine.p.vi", "Imaginary part of the voltage [1]", "B1.p.vi", 1,\
 5, 3, 4)
DeclareAlias2("G1.machine.p.ir", "Real part of the current [1]", \
"transformer.p.ir", -1, 5, 24, 132)
DeclareAlias2("G1.machine.p.ii", "Imaginary part of the current [1]", \
"transformer.p.ii", -1, 5, 25, 132)
DeclareState("G1.machine.delta", "Rotor angle (rad) [rad|rad]", 0, 0.0, 0.0,0.0,\
0.0,0,544)
DeclareDerivative("G1.machine.der(delta)", "der(Rotor angle (rad)) [rad/s]", 0.0,\
 0.0,0.0,0.0,0,512)
DeclareState("G1.machine.w", "Rotor speed (pu) [1]", 1, 1, 0.0,0.0,0.0,0,544)
DeclareDerivative("G1.machine.der(w)", "der(Rotor speed (pu)) [s-1]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("G1.machine.v", "Generator terminal voltage (pu) [1]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("G1.machine.P", "Active power (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("G1.machine.Q", "Reactive power (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("G1.machine.vf", "Field voltage (pu) [1]", "G1.machine.vf00", 1, 5,\
 129, 0)
DeclareAlias2("G1.machine.vf0", "Initial field voltage (pu) [1]", \
"G1.machine.vf00", 1, 5, 129, 0)
DeclareAlias2("G1.machine.pm0", "Initial mechanical power (pu) [1]", \
"G1.machine.pm00", 1, 5, 122, 0)
DeclareAlias2("G1.machine.pm", "Mechanical power (pu) [1]", "G1.machine.pm00", 1,\
 5, 122, 0)
DeclareVariable("G1.machine.anglev", " Bus voltage angle (rad) [rad|deg]", 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("G1.machine.vd", "d-axis voltage (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("G1.machine.vq", "q-axis voltage (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("G1.machine.id", "d-axis currrent (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("G1.machine.iq", "q-axis current (pu) [1]", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("G1.machine.pe", "electrical power transmitted through the air-gap [1]",\
 0.0, 0.0,0.0,0.0,0,2560)
DeclareVariable("G1.machine.vf_MB", "field voltage on machine base [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.w_b", "Base frequency in rad/s [rad/s]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.S_SBtoMB", "S(system base) -> S(machine base) [1]", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.I_MBtoSB", "I(machine base) -> I(system base) [1]", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.V_MBtoSB", "V(machine base) -> V(system base) [1]", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.Z_MBtoSB", "Z(machine base) -> Z(system base) [1]", \
0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.p0", "Initial active power generation in pu (system base) [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.q0", "Initial reactive power generation in pu (system base) [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.Vt0.re", "Real part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.Vt0.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.S0.re", "Real part of complex number [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.S0.im", "Imaginary part of complex number [1]", 0.0,\
 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.I0.re", "Real part of complex number", 0.0, 0.0,0.0,\
0.0,0,2561)
DeclareVariable("G1.machine.I0.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.vr0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.vi0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.ir0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.ii0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.xq0", "used for setting the initial rotor angle [1]",\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.delta0", "Init. val. rotor angle [rad|deg]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.Vdq0.re", "Real part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.Vdq0.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.Idq0.re", "Real part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.Idq0.im", "Imaginary part of complex number", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.vd0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.vq0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.id0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.iq0", "Init. val. [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.pm00", "Init. val. (pu, system base) [1]", 0.0, \
0.0,0.0,0.0,0,2561)
DeclareParameter("G1.machine.xd", "d-axis synchronous reactance (pu) [1]", 50, \
1.81, 0.0,0.0,0.0,0,560)
DeclareParameter("G1.machine.xq", "q-axis synchronous reactance (pu) [1]", 51, \
1.76, 0.0,0.0,0.0,0,560)
DeclareParameter("G1.machine.x1q", "q-axis transient reactance (pu) [1]", 52, \
0.65, 0.0,0.0,0.0,0,560)
DeclareParameter("G1.machine.x2d", "d-axis sub-transient reactance (pu) [1]", 53,\
 0.23, 0.0,0.0,0.0,0,560)
DeclareParameter("G1.machine.x2q", "q-axis sub-transient reactance (pu) [1]", 54,\
 0.25, 0.0,0.0,0.0,0,560)
DeclareParameter("G1.machine.T1d0", "d-axis open circuit transient time constant (s)",\
 55, 8, 0.0,0.0,0.0,0,560)
DeclareParameter("G1.machine.T1q0", "q-axis open circuit transient time constant (s)",\
 56, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("G1.machine.T2d0", "d-axis open circuit transient time constant (s)",\
 57, 0.03, 0.0,0.0,0.0,0,560)
DeclareParameter("G1.machine.T2q0", "q-axis open circuit transient time constant (s)",\
 58, 0.07, 0.0,0.0,0.0,0,560)
DeclareParameter("G1.machine.Taa", "d-axis aditional leakage time constant (s)",\
 59, 0, 0.0,0.0,0.0,0,560)
DeclareState("G1.machine.e1q", "q-axis transient voltage [1]", 2, 0.0, 0.0,0.0,\
0.0,0,544)
DeclareDerivative("G1.machine.der(e1q)", "der(q-axis transient voltage) [s-1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareState("G1.machine.e1d", "d-axis transient voltage [1]", 3, 0.0, 0.0,0.0,\
0.0,0,544)
DeclareDerivative("G1.machine.der(e1d)", "der(d-axis transient voltage) [s-1]", \
0.0, 0.0,0.0,0.0,0,512)
DeclareState("G1.machine.e2q", "q-axis sub-transient voltage [1]", 4, 0.0, \
0.0,0.0,0.0,0,544)
DeclareDerivative("G1.machine.der(e2q)", "der(q-axis sub-transient voltage) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("G1.machine.e2d", "d-axis sub-transient voltage [1]", 5, 0.0, \
0.0,0.0,0.0,0,544)
DeclareDerivative("G1.machine.der(e2d)", "der(d-axis sub-transient voltage) [s-1]",\
 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("G1.machine.e2q0", "Initialitation [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.e2d0", "Initialitation [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.e1d0", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.K1", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.K2", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.e1q0", "[1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("G1.machine.vf00", "Init. val. (pu, SB) [1]", 0.0, 0.0,0.0,0.0,0,2561)
DeclareAlias2("G1.pwPin.vr", "Real part of the voltage [1]", "B1.p.vr", 1, 5, 2,\
 4)
DeclareAlias2("G1.pwPin.vi", "Imaginary part of the voltage [1]", "B1.p.vi", 1, 5,\
 3, 4)
DeclareAlias2("G1.pwPin.ir", "Real part of the current [1]", "transformer.p.ir", -1,\
 5, 24, 132)
DeclareAlias2("G1.pwPin.ii", "Imaginary part of the current [1]", \
"transformer.p.ii", -1, 5, 25, 132)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(W_,91), DYNX(W_,120), 5);
DoRemember_(DYNX(W_,92), DYNX(W_,121), 4);
DoRememAcc_(DYNX(W_,37), 0.0, 6);
DoRememAcc_(DYNX(W_,36), 0.0, 7);
DoRememAcc_(DYNX(W_,59), 0.0, 8);
DoRememAcc_(DYNX(W_,58), 0.0, 9);
DoRemember_(DYNX(W_,57), 0.0, 3);
DoRemember_(DYNX(W_,56), 0.0, 2);
DoRemember_(DYNX(W_,27), 0.0, 0);
DoRemember_(DYNX(W_,26), 0.0, 1);
EndEqBlock
EndDataBlock

BreakSectionFunctionStart(0);
BreakSectionFunctionCallNew(1);
BreakSectionFunctionEnd()
